services:
  wordpress:
    # Use 'build: .' to build the image from the Dockerfile in the current directory
    build: .
    container_name: my-wordpress
    restart: always
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: admin
      WORDPRESS_DB_PASSWORD: admin
      WORDPRESS_DB_NAME: wordpress
      GCE_URL: http://localhost:5500
    volumes:
      - ./data/wordpress:/var/www/html
      - ./uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
      - ./src:/var/www/html/wp-content/themes/hello-elementor-child/src
  db:
    image: mysql:5.7
    container_name: my-mysql
    platform: linux/amd64  # for macos
    restart: always
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_ROOT_PASSWORD: admin
    volumes:
      - ./data/mysql:/var/lib/mysql
  nginx:
    image: nginx:latest
    container_name: my-nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    restart: always
    volumes:
      # Wymaga dodania pliku nginx.conf do konfiguracji proxy
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      # Wymaga wolumenów do przechowywania certyfikatów SSL/TLS
      - ./ssl:/etc/nginx/ssl
    depends_on:
      - wordpress
  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      # Wolumeny współdzielone z Nginx do zapisu certyfikatów
      - ./ssl:/etc/letsencrypt
      - ./nginx/www:/var/www/certbot
    # Używamy tylko do ręcznego generowania certyfikatów
    command: [ "/bin/true" ]
    # Usunęliśmy to polecenie, ponieważ wymaga to ręcznego uruchomienia
    # w celu wygenerowania pierwszego certyfikatu.

networks:
  default:
    name: wordpress-network
